version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 434185086652.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPOSITORY_URI=434185086652.dkr.ecr.ap-northeast-1.amazonaws.com/mk-ecr-repository-dev
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo '[{"name":"mk-ecs-container-dev","imageUri":"'"$REPOSITORY_URI:$IMAGE_TAG"'"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
