version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # 必要なら Node.js に置換可
    commands:
      - echo Installing packages...
  build:
    commands:
      - echo Build started on `date`
      - echo Build step can be customized here
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
